### ISSUE TITLE
connection refused (error 500)

### ISSUE THREAD

**Issue by Free16t** [jplusplus/detective.io#696]
Hi, 

I'm working on the installation of detective on my archlinux. 
The installation is ok, I can start detective, create the skeleton and so one but when suddenly (after trying to publish) I have this error(on each page now, here the message when I go to my user account):

>[02/May/2015 07:42:15] "GET /partial/main/user/user.html HTTP/1.1" 200 1095
Internal Server Error: /api/detective/common/v1/summary/mine/
Traceback (most recent call last):
  File "/home/pierre/detective/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/pierre/detective/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 77, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/pierre/detective/venv/lib/python2.7/site-packages/tastypie/resources.py", line 195, in wrapper
    response = callback(request, *args, **kwargs)
  File "/home/pierre/detective/venv/lib/python2.7/site-packages/tastypie/resources.py", line 435, in dispatch_detail
    return self.dispatch('detail', request, **kwargs)
  File "/home/pierre/detective/venv/lib/python2.7/site-packages/tastypie/resources.py", line 458, in dispatch
    response = method(request, **kwargs)
  File "/home/pierre/detective/venv/lib/python2.7/site-packages/tastypie/resources.py", line 1295, in get_detail
    obj = self.cached_obj_get(bundle=basic_bundle, **self.remove_api_resource_names(kwargs))
  File "/home/pierre/detective/venv/lib/python2.7/site-packages/tastypie/resources.py", line 1113, in cached_obj_get
    cached_bundle = self.obj_get(bundle=bundle, **kwargs)
  File "/home/pierre/detective/app/detective/topics/common/summary.py", line 83, in obj_get
    return self.discover_method(request, **kwargs)
  File "/home/pierre/detective/app/detective/topics/common/summary.py", line 64, in discover_method
    content = method(kwargs["bundle"], request)
  File "/home/pierre/detective/app/detective/topics/common/summary.py", line 224, in summary_mine
    matches      = connection.cypher(query).to_dicts()
  File "/home/pierre/detective/venv/lib/python2.7/site-packages/neo4django/db/__init__.py", line 115, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/home/pierre/detective/venv/lib/python2.7/site-packages/neo4django/utils.py", line 494, in __getitem__
    conn = Client('http://%s:%d%s' % (db['HOST'], db['PORT'], db['ENDPOINT']), **db['OPTIONS'])
  File "/home/pierre/detective/venv/lib/python2.7/site-packages/neo4django/neo4jclient.py", line 30, in __init__
    super(EnhancedGraphDatabase, self).__init__(*args, **kwargs)
  File "/home/pierre/detective/venv/lib/python2.7/site-packages/neo4jrestclient/client.py", line 84, in __init__
    response, content = Request(**self._auth).get(self.url)
  File "/home/pierre/detective/venv/lib/python2.7/site-packages/neo4jrestclient/request.py", line 144, in get
    return self._request('GET', url, headers=headers)
  File "/home/pierre/detective/venv/lib/python2.7/site-packages/neo4django/db/__init__.py", line 61, in _request
    headers)
  File "/home/pierre/detective/venv/lib/python2.7/site-packages/neo4jrestclient/request.py", line 306, in _request
    body=body)
  File "/home/pierre/detective/venv/lib/python2.7/site-packages/httplib2/__init__.py", line 1608, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/home/pierre/detective/venv/lib/python2.7/site-packages/httplib2/__init__.py", line 1350, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/home/pierre/detective/venv/lib/python2.7/site-packages/httplib2/__init__.py", line 1272, in _conn_request
    conn.connect()
  File "/home/pierre/detective/venv/lib/python2.7/site-packages/httplib2/__init__.py", line 928, in connect
    raise socket.error, msg
error: [Errno 111] Connection refused
[02/May/2015 07:42:15] "GET /api/detective/common/v1/summary/mine/ HTTP/1.1" 500 17745

Have you ever seen this issue?
What can I do?

Sincerely

**Comment by Pirhoo** [comment]
Hi,

could you give me more information about your Neo4j setup? It looks like it's the problem here...

Best

**Comment by Free16t** [comment]
Hi, 

Well my Neo4j setup is linked to the install by the Makefile. I did nothing specific. 

Sincerely
